{% set name = "django-entangled" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b432fb7d0da89ada6320dc4a29e532a74e2443be8259acbdaab3e53395f65282

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - django >=2.1

test:
  imports:
    - entangled
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jrief/django-entangled
  summary: Edit JSON field using Django Model Form
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
